/** Webhook bodies shaped like GitLab's documented examples (docs.gitlab.com/user/project/integrations/webhook_events). */

const user = {
  id: 11,
  name: 'Ana Example',
  username: 'ana',
  avatar_url: 'https://gitlab.example.com/ana.png',
  email: '[REDACTED]',
}
const project = {
  id: 42,
  name: 'billing',
  description: 'Billing service',
  web_url: 'https://gitlab.example.com/acme/platform/billing',
  git_ssh_url: 'git@gitlab.example.com:acme/platform/billing.git',
  git_http_url: 'https://gitlab.example.com/acme/platform/billing.git',
  namespace: 'platform',
  path_with_namespace: 'acme/platform/billing',
  default_branch: 'main',
}
const repository = {
  name: 'billing',
  url: 'git@gitlab.example.com:acme/platform/billing.git',
  homepage: 'https://gitlab.example.com/acme/platform/billing',
}

export const mergeRequest = (action: string, extra: Record<string, unknown> = {}) => ({
  object_kind: 'merge_request',
  event_type: 'merge_request',
  user,
  project,
  repository,
  object_attributes: {
    id: 1012,
    iid: 12,
    target_branch: 'main',
    source_branch: 'mp/billing-bot/fix-rounding',
    source_project_id: 42,
    author_id: 7,
    title: 'Fix rounding in invoices',
    description: 'Rounds to cents.',
    state: action === 'merge' ? 'merged' : action === 'close' ? 'closed' : 'opened',
    merge_status: 'can_be_merged',
    detailed_merge_status: 'mergeable',
    draft: false,
    work_in_progress: false,
    url: 'https://gitlab.example.com/acme/platform/billing/-/merge_requests/12',
    last_commit: { id: 'da1560886d4f094c3e6c9ef40349f7d38b5d27d7', title: 'Round to cents', message: 'Round to cents\n' },
    action,
    ...extra,
  },
  labels: [{ id: 206, title: 'bug', color: '#dc143c' }],
  changes: {},
  assignees: [{ id: 7, name: 'Billing Bot (AI)', username: 'billing-bot' }],
  reviewers: [{ id: 11, name: 'Ana Example', username: 'ana' }],
})

export const mrNote = (extra: Record<string, unknown> = {}) => ({
  object_kind: 'note',
  event_type: 'note',
  user,
  project_id: 42,
  project,
  repository,
  object_attributes: {
    id: 1244,
    note: 'Please handle\nnegative amounts.',
    noteable_type: 'MergeRequest',
    author_id: 11,
    discussion_id: 'd1a2b3c4d5e6f7a8b9c0d1a2b3c4d5e6f7a8b9c0',
    type: 'DiffNote',
    position: {
      base_sha: 'a',
      start_sha: 'b',
      head_sha: 'c',
      old_path: 'src/app.ts',
      new_path: 'src/app.ts',
      old_line: null,
      new_line: 2,
    },
    system: false,
    url: 'https://gitlab.example.com/acme/platform/billing/-/merge_requests/12#note_1244',
    ...extra,
  },
  merge_request: {
    id: 1012,
    iid: 12,
    title: 'Fix rounding in invoices',
    source_branch: 'mp/billing-bot/fix-rounding',
    target_branch: 'main',
    state: 'opened',
  },
})

export const issueNote = () => ({
  object_kind: 'note',
  event_type: 'note',
  user,
  project_id: 42,
  project,
  object_attributes: {
    id: 1241,
    note: 'Seen again today.',
    noteable_type: 'Issue',
    discussion_id: 'aaa111',
    type: null,
    url: 'https://gitlab.example.com/acme/platform/billing/-/issues/3#note_1241',
  },
  issue: { id: 3003, iid: 3, title: 'Invoices round wrong', state: 'opened' },
})

export const commitNote = () => ({
  object_kind: 'note',
  user,
  project,
  object_attributes: { id: 1243, note: 'Nice commit', noteable_type: 'Commit' },
  commit: { id: 'cfe32cf61b73a0d5e9f13e774abde7ff789b1660' },
})

export const pipeline = (status: string, withMr = true, builds?: any[]) => ({
  object_kind: 'pipeline',
  object_attributes: {
    id: 900,
    iid: 90,
    name: null,
    ref: withMr ? 'refs/merge-requests/12/head' : 'main',
    tag: false,
    sha: 'feedfacefeedfacefeedfacefeedfacefeedface',
    before_sha: '0000000000000000000000000000000000000000',
    source: withMr ? 'merge_request_event' : 'push',
    status,
    detailed_status: status,
    stages: ['build', 'test'],
    created_at: '2026-09-28 10:00:00 UTC',
    finished_at: '2026-09-28 10:05:00 UTC',
    duration: 300,
    url: 'https://gitlab.example.com/acme/platform/billing/-/pipelines/900',
  },
  merge_request: withMr
    ? {
        id: 1012,
        iid: 12,
        title: 'Fix rounding in invoices',
        source_branch: 'mp/billing-bot/fix-rounding',
        target_branch: 'main',
        state: 'opened',
        url: 'https://gitlab.example.com/acme/platform/billing/-/merge_requests/12',
      }
    : null,
  user,
  project,
  commit: { id: 'feedface', message: 'Round to cents', title: 'Round to cents' },
  builds: builds ?? [
    { id: 5000, stage: 'build', name: 'build', status: 'success', allow_failure: false },
    {
      id: 5001,
      stage: 'test',
      name: 'test',
      status: status === 'failed' ? 'failed' : 'success',
      failure_reason: 'script_failure',
      allow_failure: false,
    },
    { id: 5002, stage: 'test', name: 'lint', status: status === 'failed' ? 'failed' : 'success', allow_failure: true },
  ],
})

export const job = (status: string, ref = 'refs/merge-requests/12/head') => ({
  object_kind: 'build',
  ref,
  tag: false,
  before_sha: '2293ada6b400935a1378653304eaf6221e0fdb8f',
  sha: 'feedfacefeedfacefeedfacefeedfacefeedface',
  retries_count: 0,
  build_id: 5001,
  build_name: 'test',
  build_stage: 'test',
  build_status: status,
  build_created_at: '2026-09-28 10:00:00 UTC',
  build_started_at: '2026-09-28 10:01:00 UTC',
  build_finished_at: '2026-09-28 10:02:00 UTC',
  build_duration: 60,
  build_allow_failure: false,
  build_failure_reason: status === 'failed' ? 'script_failure' : 'unknown_failure',
  pipeline_id: 900,
  project_id: 42,
  project_name: 'Acme / Platform / billing',
  user,
  commit: { id: 900, sha: 'feedface', message: 'Round to cents', status },
  repository,
  project,
})

export const push = (extra: Record<string, unknown> = {}) => ({
  object_kind: 'push',
  event_name: 'push',
  before: '95790bf891e76fee5e1747ab589903a6a1f80f22',
  after: 'da1560886d4f094c3e6c9ef40349f7d38b5d27d7',
  ref: 'refs/heads/mp/billing-bot/fix-rounding',
  ref_protected: false,
  checkout_sha: 'da1560886d4f094c3e6c9ef40349f7d38b5d27d7',
  user_id: 7,
  user_name: 'Billing Bot (AI)',
  user_username: 'billing-bot',
  user_email: '',
  project_id: 42,
  project,
  repository,
  commits: [
    {
      id: 'b6568db1bc1dcd7f8b4d5a946b0b91f9dacd7327',
      message: 'Round to cents\n\nSession: ses_01',
      title: 'Round to cents',
      timestamp: '2026-09-28T10:00:00+00:00',
      author: { name: 'Billing Bot (AI)', email: 'billing-bot@example.com' },
    },
    {
      id: 'da1560886d4f094c3e6c9ef40349f7d38b5d27d7',
      message: 'Add tests',
      title: 'Add tests',
      timestamp: '2026-09-28T10:01:00+00:00',
      author: { name: 'Billing Bot (AI)', email: 'billing-bot@example.com' },
    },
  ],
  total_commits_count: 2,
  ...extra,
})

export const issue = (action: string, extra: Record<string, unknown> = {}) => ({
  object_kind: 'issue',
  event_type: 'issue',
  user,
  project,
  object_attributes: {
    id: 3003,
    iid: 3,
    title: 'Invoices round wrong',
    description: 'Amounts like 0.105 round down.',
    state: action === 'close' ? 'closed' : 'opened',
    confidential: false,
    url: 'https://gitlab.example.com/acme/platform/billing/-/issues/3',
    action,
    ...extra,
  },
  labels: [{ id: 206, title: 'bug' }],
  changes: action === 'update' ? { labels: { previous: [], current: [{ title: 'bug' }] } } : {},
  assignees: [{ id: 7, username: 'billing-bot', name: 'Billing Bot (AI)' }],
})
