/** Tools only reviewer sessions get. */
export const REVIEWER_ONLY_TOOLS = ['checklist.record_review'] as const

/**
 * Every stdlib tool except the reviewer-only ones, sorted. Includes the git,
 * env and code tools; when they aren't registered (no git cache, container
 * runtime or sandbox) the runner simply doesn't offer them.
 */
export const DEFAULT_TOOLSET: readonly string[] = [
  'chat.add_member',
  'chat.archive',
  'chat.attachment_text',
  'chat.create_channel',
  'chat.delete',
  'chat.edit',
  'chat.invite',
  'chat.post',
  'chat.react',
  'chat.read',
  'chat.remove_member',
  'chat.reply',
  'chat.save_attachment',
  'chat.search',
  'checklist.add_item',
  'checklist.check',
  'checklist.request_review',
  'checklist.show',
  'code.reset',
  'code.run',
  'directory.find_contact',
  'directory.find_procedure',
  'directory.find_project',
  'directory.get_contact',
  'directory.get_procedure',
  'directory.get_project',
  'directory.projects_of',
  'docs.backlinks',
  'docs.list',
  'docs.read',
  'docs.search',
  'docs.write',
  'docs.write_chapter',
  'env.down',
  'env.exec',
  'env.logs',
  'env.preview',
  'env.screenshot',
  'env.up',
  'fs.delete',
  'fs.list',
  'fs.move',
  'fs.read',
  'fs.share',
  'fs.write',
  'git.checkout',
  'git.commit',
  'git.diff',
  'git.edit_file',
  'git.list_files',
  'git.log',
  'git.push',
  'git.read_file',
  'git.status',
  'git.write_file',
  'image.view',
  'memory.forget',
  'memory.link',
  'memory.recall',
  'memory.remember',
  'memory.verify',
  'procedures.run',
  'sessions.commit',
  'sessions.compact',
  'sessions.create',
  'sessions.discard',
  'sessions.finish',
  'sessions.fork',
  'sessions.get',
  'sessions.link',
  'sessions.list',
  'sessions.look_up',
  'sessions.loop',
  'sessions.message',
  'sessions.offload',
  'sessions.restore',
  'sessions.rewind',
  'sessions.save_metadata',
  'sessions.save_template',
  'sessions.search',
  'sessions.tree',
  'sessions.unlink',
  'sessions.wait',
  'skills.list',
  'skills.load',
  'subscriptions.list',
  'subscriptions.subscribe',
  'subscriptions.unsubscribe',
  'time.now',
  'triggers.create',
  'triggers.disable',
  'triggers.list',
  'triggers.update',
]

/** A fresh-context reviewer: read-only tools plus recording its verdict. */
export const REVIEWER_TOOLSET: readonly string[] = [
  'checklist.record_review',
  'checklist.show',
  'docs.read',
  'env.logs',
  'git.diff',
  'sessions.get',
  'time.now',
]

/**
 * Tools a router context never needs: it routes, it doesn't do the work. The
 * sessions it starts get the full toolset. Leaving these out keeps every
 * router call small (about a third fewer tool definitions).
 */
export const ROUTER_EXCLUDED_TOOLS: readonly string[] = [
  'git.**',
  'env.**',
  'fs.**',
  'docs.write',
  'docs.write_chapter',
  'chat.add_member',
  'chat.archive',
  'chat.attachment_text',
  'chat.create_channel',
  'chat.delete',
  'chat.edit',
  'chat.remove_member',
  'chat.save_attachment',
  'sessions.offload',
  'sessions.restore',
  'sessions.save_template',
  'triggers.**',
]
